[package]
name = "yfs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
bincode = "1.3.3"
bitvec = "1.0.1"
clap = { version = "3.1.6", features = ["cargo"] }
fuser = "0.12"
libc = "0.2"
serde = { version = "1.0.160", features = ["derive"] }
serde_repr = "0.1.18"
